### ISSUE TITLE
Remove formtastic

### ISSUE THREAD

**Issue by Br3nda** [rabid/nzsl-online#42]
Formtastic is used in the admin UI. Let's use bootstrap and remove our formtastic.css file.

**Comment by Br3nda** [comment]
@vinithanatarajan i think this one was done by you?

**Comment by vinithanatarajan** [comment]
@Br3nda yes I did that.

**Comment by vinithanatarajan** [comment]
This story is done but didn't use bootstrap, used foundation forms.

**Comment by Br3nda** [comment]
:+1:
